# Common configuration settings

[messages]
    # Title shown to players before login
    loginTitle = "AuthShield.title"
    
    # Subtitle shown to players before login
    loginSubtitle = "AuthShield.subtitle"
    
    # Message shown to unregistered players
    register = "AuthShield.register"
    
    # Message shown when login is successful
    loginSuccess = "AuthShield.login.success"
    
    # Message shown when player tries to login again
    alreadyLoggedIn = "AuthShield.login.already"
    
    # Message shown when password is incorrect
    incorrectPassword = "AuthShield.login.incorrect"
    
    # Message shown when player is kicked for not logging in
    loginTimeout = "AuthShield.login.timeout"

[settings]
    # Time in seconds before kicking player if not logged in
    loginTimeoutSeconds = 60
    
    # Default gamemode for players before login
    preLoginGamemode = "spectator"
    
    # Effects applied to players before login
    # Format: "effect_id:amplifier"
    preLoginEffects = [
        "minecraft:slow_falling:255",
        "minecraft:resistance:255",
        "minecraft:jump:128",
        "minecraft:slowness:255"
    ] 